# Generated by Django 4.0.5 on 2022-07-10 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Cl', 'Clothes'), ('El', 'Electronics'), ('Gr', 'Groceries'), ('Je', 'Jewelery'), ('St', 'Stationery')], max_length=2),
        ),
    ]
